const baseUrl = "http://localhost:3000"

const userLogin = "/login/session"
const getPacientes = "/paciente"
const getPsicologo = "/psicologo"
const getConsultas = "/consultas"
const pacienteSaveUpdate = "/pacienteSaveUpdate"
const agendarConsulta = "/agendarConsulta"
const cancelarConsulta = "/cancelarConsulta"
const registrarAvaliacao = "/registrarAvaliacao"
const getAvaliacao = "/avaliacoes"
const getAllAvaliacao = "/avaliacoesAll"